App\Entity\Task:
    type: entity
    id:
        task:
            type: integer
            generator: { strategy: AUTO }
            - NotBlank: ~
    fields:
        dueDate:
            type: date
            - NotBlank: ~
            - Type: \DateTime
